# Generated by Django 3.0.6 on 2020-05-25 19:53

import autoslug.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, verbose_name='Service Name')),
                ('inv_cost', models.DecimalField(decimal_places=2, help_text='The investment cost refers to the money invested to perform the service (this infotmation is used to obtain profit). Theinvestment cost can be zero.', max_digits=19, verbose_name='Cost Investment')),
                ('sal_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Sale Price')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Aditional Service Informarion.')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Date Added')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('pub_date__month',))),
            ],
        ),
    ]
