# Generated by Django 3.0.6 on 2020-05-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='inv_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The investment cost refers to the money invested to perform the service (this infotmation is used to obtain profit). Theinvestment cost can be zero.', max_digits=19, verbose_name='Cost Investment'),
        ),
        migrations.AlterField(
            model_name='services',
            name='sal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Sale Price'),
        ),
    ]
