# Generated by Django 3.0.6 on 2020-05-27 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_auto_20200525_2255'),
    ]

    operations = [
        migrations.AlterField(
            model_name='services',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Additional Service Information.'),
        ),
        migrations.AlterField(
            model_name='services',
            name='inv_cost',
            field=models.DecimalField(decimal_places=2, default=0, help_text='The investment cost refers to the money invested to perform the service (this information is used to obtain profit). Theinvestment cost can be zero.', max_digits=19, verbose_name='Cost Investment'),
        ),
    ]
