# Generated by Django 3.0.6 on 2020-05-24 20:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Units',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Products',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=8)),
                ('image', models.ImageField(upload_to='')),
                ('name', models.CharField(max_length=32)),
                ('q', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('q_reserve', models.PositiveSmallIntegerField(help_text='is the minimum quantity of the product that indicates that you must buy more product.', verbose_name='Quantity Reserve')),
                ('pur_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Purchase Price')),
                ('sal_price', models.DecimalField(decimal_places=2, max_digits=19, verbose_name='Sale Price')),
                ('info', models.TextField(verbose_name='Aditional Product informariom.')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventories.Categories')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='inventories.Units')),
            ],
        ),
    ]
