# Generated by Django 3.0.6 on 2020-05-24 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='products',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Aditional Product informariom.'),
        ),
        migrations.AlterField(
            model_name='products',
            name='q_reserve',
            field=models.PositiveSmallIntegerField(help_text='Is the minimum quantity of the product that indicates that you must buy more product.', verbose_name='Quantity Reserve'),
        ),
    ]
