# Generated by Django 3.0.6 on 2020-05-24 22:16

import autoslug.fields
import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0003_products_pub_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='slug',
            field=autoslug.fields.AutoSlugField(default='ddd', editable=False, populate_from='name', unique_with=('pub_date__month',)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='products',
            name='info',
            field=models.TextField(blank=True, null=True, verbose_name='Aditional Product Informarion.'),
        ),
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 22, 16, 14, 836458, tzinfo=utc), verbose_name='Date Added'),
        ),
    ]
