# Generated by Django 3.0.6 on 2020-05-24 22:16

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0004_auto_20200525_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 5, 24, 22, 16, 54, 668074, tzinfo=utc), verbose_name='Date Added'),
        ),
    ]
