# Generated by Django 3.0.6 on 2020-05-25 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0005_auto_20200525_0116'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pub_date',
            field=models.DateTimeField(auto_now=True, verbose_name='Date Added'),
        ),
    ]
