# Generated by Django 3.0.6 on 2020-05-25 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventories', '0006_auto_20200525_1821'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='pur_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Purchase Price'),
        ),
        migrations.AlterField(
            model_name='products',
            name='sal_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Sale Price'),
        ),
    ]
