# Generated by Django 3.0.6 on 2020-05-27 15:26

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('services', '0003_auto_20200527_1826'),
        ('inventories', '0008_auto_20200527_1826'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentMethods',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
            ],
        ),
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('q', models.PositiveSmallIntegerField(verbose_name='Quantity')),
                ('sale', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Sale KSh')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=19, verbose_name='Subtotal KSh')),
                ('paid', models.BooleanField(default=True, help_text='Paid, unchecked if receivables', verbose_name='Paid?')),
                ('client', models.CharField(blank=True, max_length=128, null=True, verbose_name='Client Name')),
                ('info', models.TextField(blank=True, null=True, verbose_name='Additional Information.')),
                ('pub_date', models.DateTimeField(auto_now=True, verbose_name='Date Added')),
                ('slug', autoslug.fields.AutoSlugField(editable=False, populate_from='name', unique_with=('pub_date__month',))),
                ('p_method', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.PaymentMethods', verbose_name='Payment Method')),
                ('product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='inventories.Products')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='services.Services')),
                ('tag', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='sales.Tags')),
            ],
        ),
    ]
